"""Bidirectional MUMPS ↔ Python name translation.

This module provides the **single source of truth** for translating
MUMPS identifiers to valid Python identifiers and back.

Constitution VII: Single implementation shared by codegen (compile time)
and runtime (dynamic resolution) to ensure variable names are consistent
across all code paths.

Feature: 018-unified-variable-system
Requirements: FR-005 through FR-009
"""

from __future__ import annotations

import keyword
import re
from typing import ClassVar, Set


class NameTranslator:
    """Bidirectional MUMPS ↔ Python name translation.

    Translation rules (applied in order):
    1. Empty string: "" → "_preamble" (labelless preamble)
    2. % prefix: %FOO → _pct_FOO
    3. Pure numeric: 01 → _n_01
    4. Python keyword: if → _m_if
    5. Otherwise: identity (MUMPS names are usually valid Python)

    The prefixes are chosen to be unambiguous:
    - _pct_ can't conflict with MUMPS names (MUMPS doesn't allow underscore prefix)
    - _n_ can't conflict (same reason)
    - _m_ can't conflict (same reason)

    Can be used as static methods or as an instance for backward compatibility.
    """

    # Python keywords that need escaping
    PYTHON_KEYWORDS: ClassVar[Set[str]] = set(keyword.kwlist)

    # Pattern for pure numeric strings (valid MUMPS labels, invalid Python)
    _NUMERIC_PATTERN: ClassVar[re.Pattern[str]] = re.compile(r"^[0-9]+$")

    # Pattern for valid MUMPS variable names (not subscripted)
    # Must start with letter or %, followed by alphanumerics
    _MUMPS_NAME_PATTERN: ClassVar[re.Pattern[str]] = re.compile(
        r"^[%A-Za-z][A-Za-z0-9]*$"
    )

    @staticmethod
    def to_python(mumps_name: str) -> str:
        """Translate MUMPS identifier to valid Python identifier.

        Args:
            mumps_name: A valid MUMPS identifier

        Returns:
            A valid Python identifier

        Rules:
            ""     → _preamble  (empty/labelless preamble)
            %NAME  → _pct_NAME  (percent-prefixed)
            01     → _n_01      (numeric-prefixed)
            if     → _m_if      (Python keyword collision)
            FOO    → FOO        (unchanged)

        Invariant: from_python(to_python(x)) == x for all valid MUMPS names

        Examples:
            >>> NameTranslator.to_python("TEST")
            'TEST'
            >>> NameTranslator.to_python("%START")
            '_pct_START'
            >>> NameTranslator.to_python("01")
            '_n_01'
            >>> NameTranslator.to_python("if")
            '_m_if'
            >>> NameTranslator.to_python("")
            '_preamble'
        """
        # Rule 0: Empty label (labelless preamble)
        if not mumps_name:
            return "_preamble"

        # Rule 1: % prefix
        if mumps_name.startswith("%"):
            return "_pct_" + mumps_name[1:]

        # Rule 2: Pure numeric
        if NameTranslator._NUMERIC_PATTERN.match(mumps_name):
            return "_n_" + mumps_name

        # Rule 3: Python keyword
        if keyword.iskeyword(mumps_name):
            return "_m_" + mumps_name

        # Rule 4: Identity (most MUMPS names are valid Python)
        return mumps_name

    @staticmethod
    def from_python(python_name: str) -> str:
        """Translate Python identifier back to MUMPS name.

        Args:
            python_name: A Python identifier previously generated by to_python()

        Returns:
            The original MUMPS identifier

        Note: This is used by runtime when parsing variable names from
        indirection values. Example: If user sets @"_pct_FOO"=5, runtime
        needs to know this refers to MUMPS variable %FOO.

        Examples:
            >>> NameTranslator.from_python("TEST")
            'TEST'
            >>> NameTranslator.from_python("_pct_START")
            '%START'
            >>> NameTranslator.from_python("_n_01")
            '01'
            >>> NameTranslator.from_python("_m_if")
            'if'
            >>> NameTranslator.from_python("_preamble")
            ''
        """
        # Reverse rule 0: _preamble → empty (labelless preamble)
        if python_name == "_preamble":
            return ""

        if not python_name:
            return python_name

        # Reverse rule 1: _pct_ → %
        if python_name.startswith("_pct_"):
            return "%" + python_name[5:]

        # Reverse rule 2: _n_ → numeric
        if python_name.startswith("_n_"):
            return python_name[3:]

        # Reverse rule 3: _m_ → keyword
        if python_name.startswith("_m_"):
            return python_name[3:]

        # Identity
        return python_name

    @staticmethod
    def is_valid_mumps_name(name: str) -> bool:
        """Check if string is a valid MUMPS variable name.

        A valid MUMPS variable name:
        - Starts with letter or % (for system variables)
        - Followed by zero or more alphanumerics
        - Does NOT include subscripts (no parentheses)

        Args:
            name: String to validate

        Returns:
            True if valid MUMPS identifier

        Used by: IndirectionResolver to validate NAME indirection results.
        If this returns False for a resolved value, VAREXPECTED error is raised.

        Examples:
            >>> NameTranslator.is_valid_mumps_name("X")
            True
            >>> NameTranslator.is_valid_mumps_name("%FOO")
            True
            >>> NameTranslator.is_valid_mumps_name("A123")
            True
            >>> NameTranslator.is_valid_mumps_name("1+1")
            False
            >>> NameTranslator.is_valid_mumps_name("")
            False
            >>> NameTranslator.is_valid_mumps_name("X(1)")
            False
        """
        if not name:
            return False
        return bool(NameTranslator._MUMPS_NAME_PATTERN.match(name))

    # Instance methods for backward compatibility with old NameTranslator usage
    def translate(self, mumps_name: str) -> str:
        """Instance method wrapper for to_python (backward compatibility)."""
        return self.to_python(mumps_name)

    def reverse(self, python_name: str) -> str:
        """Instance method wrapper for from_python (backward compatibility)."""
        return self.from_python(python_name)


# Module-level convenience functions for backward compatibility
def translate_name(mumps_name: str) -> str:
    """Convenience function to translate a MUMPS name to Python.

    Deprecated: Use NameTranslator.to_python() directly.
    """
    return NameTranslator.to_python(mumps_name)


def reverse_name(python_name: str) -> str:
    """Convenience function to recover MUMPS name from Python.

    Deprecated: Use NameTranslator.from_python() directly.
    """
    return NameTranslator.from_python(python_name)


__all__ = ["NameTranslator", "translate_name", "reverse_name"]
