"""Bidirectional MUMPS ↔ Python name translation.

Canonical module for translating MUMPS identifiers to valid Python
identifiers and back. Shared by codegen (compile time) and runtime
(dynamic resolution) to ensure variable names are consistent across
all code paths.
"""

from __future__ import annotations

import keyword
import re
from typing import ClassVar, Set


class NameTranslator:
    """Bidirectional MUMPS ↔ Python name translation.

    Translation rules (applied in order):
    1. Empty string: "" → "_preamble" (labelless preamble)
    2. % prefix: %FOO → _pct_FOO
    3. Pure numeric: 01 → _n_01
    4. Python keyword: if → _m_if
    5. Python stdlib module: io → io_ (avoids import collision)
    6. E743 ambiguous name: I → _a_I (avoids lint E743)
    7. Otherwise: identity (MUMPS names are usually valid Python)

    The prefixes are chosen to be unambiguous:
    - _pct_ can't conflict with MUMPS names (MUMPS doesn't allow underscore prefix)
    - _n_ can't conflict (same reason)
    - _m_ can't conflict (same reason)

    Can be used as static methods or as an instance for backward compatibility.
    """

    # Python keywords that need escaping
    PYTHON_KEYWORDS: ClassVar[Set[str]] = set(keyword.kwlist)

    # Python stdlib module names that conflict when used as import targets.
    # MUMPS routines with these names must be renamed to avoid importing
    # Python's stdlib instead of the transpiled routine.
    PYTHON_STDLIB_CONFLICTS: ClassVar[Set[str]] = {
        "abc",
        "ast",
        "copy",
        "decimal",
        "io",
        "json",
        "math",
        "os",
        "re",
        "string",
        "sys",
        "time",
        "types",
    }

    # Names that trigger E743 (ambiguous with digits: I→1, O→0, l→1)
    E743_AMBIGUOUS: ClassVar[Set[str]] = {"I", "O", "l"}

    # Pattern for pure numeric strings (valid MUMPS labels, invalid Python)
    _NUMERIC_PATTERN: ClassVar[re.Pattern[str]] = re.compile(r"^[0-9]+$")

    # Pattern for valid MUMPS variable names (not subscripted)
    # Must start with letter or %, followed by alphanumerics
    _MUMPS_NAME_PATTERN: ClassVar[re.Pattern[str]] = re.compile(
        r"^[%A-Za-z][A-Za-z0-9]*$"
    )

    # Pattern for valid global variable names (^name, not subscripted)
    _GLOBAL_NAME_PATTERN: ClassVar[re.Pattern[str]] = re.compile(
        r"^\^[%A-Za-z][A-Za-z0-9]*$"
    )

    @staticmethod
    def to_python(mumps_name: str) -> str:
        """Translate MUMPS identifier to valid Python identifier.

        Args:
            mumps_name: A valid MUMPS identifier

        Returns:
            A valid Python identifier

        Rules:
            ""     → _preamble  (empty/labelless preamble)
            %NAME  → _pct_NAME  (percent-prefixed)
            01     → _n_01      (numeric-prefixed)
            if     → _m_if      (Python keyword collision)
            io     → io_        (Python stdlib module collision)
            I      → _a_I       (E743 ambiguous name)
            FOO    → FOO        (unchanged)

        Invariant: from_python(to_python(x)) == x for all valid MUMPS names

        Examples:
            >>> NameTranslator.to_python("TEST")
            'TEST'
            >>> NameTranslator.to_python("%START")
            '_pct_START'
            >>> NameTranslator.to_python("01")
            '_n_01'
            >>> NameTranslator.to_python("if")
            '_m_if'
            >>> NameTranslator.to_python("io")
            'io_'
            >>> NameTranslator.to_python("I")
            '_a_I'
            >>> NameTranslator.to_python("")
            '_preamble'
        """
        # Rule 0: Empty label (labelless preamble)
        if not mumps_name:
            return "_preamble"

        # Rule 1: % prefix
        if mumps_name.startswith("%"):
            return "_pct_" + mumps_name[1:]

        # Rule 2: Pure numeric
        if NameTranslator._NUMERIC_PATTERN.match(mumps_name):
            return "_n_" + mumps_name

        # Rule 3: Python keyword
        if keyword.iskeyword(mumps_name):
            return "_m_" + mumps_name

        # Rule 4: Python stdlib module name collision
        if mumps_name in NameTranslator.PYTHON_STDLIB_CONFLICTS:
            return mumps_name + "_"

        # Rule 5: E743 ambiguous names (look like digits: I→1, O→0, l→1)
        if mumps_name in NameTranslator.E743_AMBIGUOUS:
            return "_a_" + mumps_name

        # Rule 6: Identity (most MUMPS names are valid Python)
        return mumps_name

    @staticmethod
    def from_python(python_name: str) -> str:
        """Translate Python identifier back to MUMPS name.

        Args:
            python_name: A Python identifier previously generated by to_python()

        Returns:
            The original MUMPS identifier

        Used by runtime when parsing variable names from indirection
        values. For example, if user sets @"_pct_FOO"=5, runtime needs
        to know this refers to MUMPS variable %FOO.

        Examples:
            >>> NameTranslator.from_python("TEST")
            'TEST'
            >>> NameTranslator.from_python("_pct_START")
            '%START'
            >>> NameTranslator.from_python("_n_01")
            '01'
            >>> NameTranslator.from_python("_m_if")
            'if'
            >>> NameTranslator.from_python("_preamble")
            ''
        """
        # Reverse rule 0: _preamble → empty (labelless preamble)
        if python_name == "_preamble":
            return ""

        if not python_name:
            return python_name

        # Reverse rule 1: _pct_ → %
        if python_name.startswith("_pct_"):
            return "%" + python_name[5:]

        # Reverse rule 2: _n_ → numeric
        if python_name.startswith("_n_"):
            return python_name[3:]

        # Reverse rule 3: _m_ → keyword
        if python_name.startswith("_m_"):
            return python_name[3:]

        # Reverse rule 4: stdlib suffix → strip trailing _
        if (
            python_name.endswith("_")
            and python_name[:-1] in NameTranslator.PYTHON_STDLIB_CONFLICTS
        ):
            return python_name[:-1]

        # Reverse rule 5: _a_ → ambiguous name
        if (
            python_name.startswith("_a_")
            and python_name[3:] in NameTranslator.E743_AMBIGUOUS
        ):
            return python_name[3:]

        # Identity
        return python_name

    @staticmethod
    def is_valid_varname(name: str, allow_subscripts: bool = False) -> bool:
        """Check if string is a valid MUMPS variable name (local or global).

        This is the unified validation function for variable names.
        Handles locals, globals, and naked references.

        Args:
            name: String to validate
            allow_subscripts: If True, accept subscripted names like X(1,2)

        Returns:
            True if valid MUMPS variable name

        Rules:
        - Local: starts with letter or %, followed by alphanumerics
        - Global: starts with ^ followed by letter or %, followed by alphanumerics
        - Naked reference: just "^" (for ^(...) syntax) - returns True
        - Subscripted: if allow_subscripts=True, strips subscripts before validating

        Examples:
            >>> NameTranslator.is_valid_varname("X")
            True
            >>> NameTranslator.is_valid_varname("%FOO")
            True
            >>> NameTranslator.is_valid_varname("^GLO")
            True
            >>> NameTranslator.is_valid_varname("^")  # Naked reference
            True
            >>> NameTranslator.is_valid_varname("X(1,2)")  # With subscripts
            False
            >>> NameTranslator.is_valid_varname("X(1,2)", allow_subscripts=True)
            True
            >>> NameTranslator.is_valid_varname("1+1")
            False
            >>> NameTranslator.is_valid_varname("")
            False
        """
        if not name:
            return False

        # Strip subscripts if allowed
        if allow_subscripts and "(" in name:
            base = name.split("(")[0]
        else:
            base = name

        # Naked reference: just "^" (valid for ^(subscripts) syntax)
        if base == "^":
            return True

        # Global variable: ^name
        if base.startswith("^"):
            return bool(NameTranslator._GLOBAL_NAME_PATTERN.match(base))

        # Local variable: name (no subscripts allowed in pattern)
        return bool(NameTranslator._MUMPS_NAME_PATTERN.match(base))


# Module-level convenience functions for backward compatibility
def translate_name(mumps_name: str) -> str:
    """Convenience wrapper around NameTranslator.to_python()."""
    return NameTranslator.to_python(mumps_name)


def is_valid_varname(name: str, allow_subscripts: bool = False) -> bool:
    """Module-level convenience for NameTranslator.is_valid_varname().

    Canonical function for MUMPS variable name validation.
    Handles local variables, global variables, and naked references.

    Args:
        name: String to validate
        allow_subscripts: If True, accept subscripted names like X(1,2)

    Returns:
        True if valid MUMPS variable name
    """
    return NameTranslator.is_valid_varname(name, allow_subscripts)


__all__ = ["NameTranslator", "translate_name", "is_valid_varname"]
